#pragma once

#include <emlite/emlite.hpp>
#include <jsbind/jsbind.hpp>
#include "CSSStyleDeclaration.hpp"
#include "enums.hpp"


class CSSPositionTryDescriptors : public CSSStyleDeclaration {
    explicit CSSPositionTryDescriptors(Handle h) noexcept;

public:
    explicit CSSPositionTryDescriptors(const emlite::Val &val) noexcept;
    static CSSPositionTryDescriptors take_ownership(Handle h) noexcept;

    CSSPositionTryDescriptors clone() const noexcept;
    jsbind::CSSOMString margin() const;
    void margin(const jsbind::CSSOMString& value);
    jsbind::CSSOMString marginTop() const;
    void marginTop(const jsbind::CSSOMString& value);
    jsbind::CSSOMString marginRight() const;
    void marginRight(const jsbind::CSSOMString& value);
    jsbind::CSSOMString marginBottom() const;
    void marginBottom(const jsbind::CSSOMString& value);
    jsbind::CSSOMString marginLeft() const;
    void marginLeft(const jsbind::CSSOMString& value);
    jsbind::CSSOMString marginBlock() const;
    void marginBlock(const jsbind::CSSOMString& value);
    jsbind::CSSOMString marginBlockStart() const;
    void marginBlockStart(const jsbind::CSSOMString& value);
    jsbind::CSSOMString marginBlockEnd() const;
    void marginBlockEnd(const jsbind::CSSOMString& value);
    jsbind::CSSOMString marginInline() const;
    void marginInline(const jsbind::CSSOMString& value);
    jsbind::CSSOMString marginInlineStart() const;
    void marginInlineStart(const jsbind::CSSOMString& value);
    jsbind::CSSOMString marginInlineEnd() const;
    void marginInlineEnd(const jsbind::CSSOMString& value);
    jsbind::CSSOMString margin_top() const;
    void margin_top(const jsbind::CSSOMString& value);
    jsbind::CSSOMString margin_right() const;
    void margin_right(const jsbind::CSSOMString& value);
    jsbind::CSSOMString margin_bottom() const;
    void margin_bottom(const jsbind::CSSOMString& value);
    jsbind::CSSOMString margin_left() const;
    void margin_left(const jsbind::CSSOMString& value);
    jsbind::CSSOMString margin_block() const;
    void margin_block(const jsbind::CSSOMString& value);
    jsbind::CSSOMString margin_block_start() const;
    void margin_block_start(const jsbind::CSSOMString& value);
    jsbind::CSSOMString margin_block_end() const;
    void margin_block_end(const jsbind::CSSOMString& value);
    jsbind::CSSOMString margin_inline() const;
    void margin_inline(const jsbind::CSSOMString& value);
    jsbind::CSSOMString margin_inline_start() const;
    void margin_inline_start(const jsbind::CSSOMString& value);
    jsbind::CSSOMString margin_inline_end() const;
    void margin_inline_end(const jsbind::CSSOMString& value);
    jsbind::CSSOMString inset() const;
    void inset(const jsbind::CSSOMString& value);
    jsbind::CSSOMString insetBlock() const;
    void insetBlock(const jsbind::CSSOMString& value);
    jsbind::CSSOMString insetBlockStart() const;
    void insetBlockStart(const jsbind::CSSOMString& value);
    jsbind::CSSOMString insetBlockEnd() const;
    void insetBlockEnd(const jsbind::CSSOMString& value);
    jsbind::CSSOMString insetInline() const;
    void insetInline(const jsbind::CSSOMString& value);
    jsbind::CSSOMString insetInlineStart() const;
    void insetInlineStart(const jsbind::CSSOMString& value);
    jsbind::CSSOMString insetInlineEnd() const;
    void insetInlineEnd(const jsbind::CSSOMString& value);
    jsbind::CSSOMString top() const;
    void top(const jsbind::CSSOMString& value);
    jsbind::CSSOMString left() const;
    void left(const jsbind::CSSOMString& value);
    jsbind::CSSOMString right() const;
    void right(const jsbind::CSSOMString& value);
    jsbind::CSSOMString bottom() const;
    void bottom(const jsbind::CSSOMString& value);
    jsbind::CSSOMString inset_block() const;
    void inset_block(const jsbind::CSSOMString& value);
    jsbind::CSSOMString inset_block_start() const;
    void inset_block_start(const jsbind::CSSOMString& value);
    jsbind::CSSOMString inset_block_end() const;
    void inset_block_end(const jsbind::CSSOMString& value);
    jsbind::CSSOMString inset_inline() const;
    void inset_inline(const jsbind::CSSOMString& value);
    jsbind::CSSOMString inset_inline_start() const;
    void inset_inline_start(const jsbind::CSSOMString& value);
    jsbind::CSSOMString inset_inline_end() const;
    void inset_inline_end(const jsbind::CSSOMString& value);
    jsbind::CSSOMString width() const;
    void width(const jsbind::CSSOMString& value);
    jsbind::CSSOMString minWidth() const;
    void minWidth(const jsbind::CSSOMString& value);
    jsbind::CSSOMString maxWidth() const;
    void maxWidth(const jsbind::CSSOMString& value);
    jsbind::CSSOMString height() const;
    void height(const jsbind::CSSOMString& value);
    jsbind::CSSOMString minHeight() const;
    void minHeight(const jsbind::CSSOMString& value);
    jsbind::CSSOMString maxHeight() const;
    void maxHeight(const jsbind::CSSOMString& value);
    jsbind::CSSOMString blockSize() const;
    void blockSize(const jsbind::CSSOMString& value);
    jsbind::CSSOMString minBlockSize() const;
    void minBlockSize(const jsbind::CSSOMString& value);
    jsbind::CSSOMString maxBlockSize() const;
    void maxBlockSize(const jsbind::CSSOMString& value);
    jsbind::CSSOMString inlineSize() const;
    void inlineSize(const jsbind::CSSOMString& value);
    jsbind::CSSOMString minInlineSize() const;
    void minInlineSize(const jsbind::CSSOMString& value);
    jsbind::CSSOMString maxInlineSize() const;
    void maxInlineSize(const jsbind::CSSOMString& value);
    jsbind::CSSOMString min_width() const;
    void min_width(const jsbind::CSSOMString& value);
    jsbind::CSSOMString max_width() const;
    void max_width(const jsbind::CSSOMString& value);
    jsbind::CSSOMString min_height() const;
    void min_height(const jsbind::CSSOMString& value);
    jsbind::CSSOMString max_height() const;
    void max_height(const jsbind::CSSOMString& value);
    jsbind::CSSOMString block_size() const;
    void block_size(const jsbind::CSSOMString& value);
    jsbind::CSSOMString min_block_size() const;
    void min_block_size(const jsbind::CSSOMString& value);
    jsbind::CSSOMString max_block_size() const;
    void max_block_size(const jsbind::CSSOMString& value);
    jsbind::CSSOMString inline_size() const;
    void inline_size(const jsbind::CSSOMString& value);
    jsbind::CSSOMString min_inline_size() const;
    void min_inline_size(const jsbind::CSSOMString& value);
    jsbind::CSSOMString max_inline_size() const;
    void max_inline_size(const jsbind::CSSOMString& value);
    jsbind::CSSOMString placeSelf() const;
    void placeSelf(const jsbind::CSSOMString& value);
    jsbind::CSSOMString alignSelf() const;
    void alignSelf(const jsbind::CSSOMString& value);
    jsbind::CSSOMString justifySelf() const;
    void justifySelf(const jsbind::CSSOMString& value);
    jsbind::CSSOMString place_self() const;
    void place_self(const jsbind::CSSOMString& value);
    jsbind::CSSOMString align_self() const;
    void align_self(const jsbind::CSSOMString& value);
    jsbind::CSSOMString justify_self() const;
    void justify_self(const jsbind::CSSOMString& value);
    jsbind::CSSOMString positionAnchor() const;
    void positionAnchor(const jsbind::CSSOMString& value);
    jsbind::CSSOMString position_anchor() const;
    void position_anchor(const jsbind::CSSOMString& value);
    jsbind::CSSOMString positionArea() const;
    void positionArea(const jsbind::CSSOMString& value);
    jsbind::CSSOMString position_area() const;
    void position_area(const jsbind::CSSOMString& value);
};

