#pragma once

#include <emlite/emlite.hpp>
#include <jsbind/jsbind.hpp>
#include "CSSStyleDeclaration.hpp"
#include "enums.hpp"


class CSSPositionTryDescriptors : public CSSStyleDeclaration {
    explicit CSSPositionTryDescriptors(Handle h) noexcept;

public:
    explicit CSSPositionTryDescriptors(const emlite::Val &val) noexcept;
    static CSSPositionTryDescriptors take_ownership(Handle h) noexcept;

    CSSPositionTryDescriptors clone() const noexcept;
    jsbind::String margin() const;
    void margin(const jsbind::String& value);
    jsbind::String marginTop() const;
    void marginTop(const jsbind::String& value);
    jsbind::String marginRight() const;
    void marginRight(const jsbind::String& value);
    jsbind::String marginBottom() const;
    void marginBottom(const jsbind::String& value);
    jsbind::String marginLeft() const;
    void marginLeft(const jsbind::String& value);
    jsbind::String marginBlock() const;
    void marginBlock(const jsbind::String& value);
    jsbind::String marginBlockStart() const;
    void marginBlockStart(const jsbind::String& value);
    jsbind::String marginBlockEnd() const;
    void marginBlockEnd(const jsbind::String& value);
    jsbind::String marginInline() const;
    void marginInline(const jsbind::String& value);
    jsbind::String marginInlineStart() const;
    void marginInlineStart(const jsbind::String& value);
    jsbind::String marginInlineEnd() const;
    void marginInlineEnd(const jsbind::String& value);
    jsbind::String margin_top() const;
    void margin_top(const jsbind::String& value);
    jsbind::String margin_right() const;
    void margin_right(const jsbind::String& value);
    jsbind::String margin_bottom() const;
    void margin_bottom(const jsbind::String& value);
    jsbind::String margin_left() const;
    void margin_left(const jsbind::String& value);
    jsbind::String margin_block() const;
    void margin_block(const jsbind::String& value);
    jsbind::String margin_block_start() const;
    void margin_block_start(const jsbind::String& value);
    jsbind::String margin_block_end() const;
    void margin_block_end(const jsbind::String& value);
    jsbind::String margin_inline() const;
    void margin_inline(const jsbind::String& value);
    jsbind::String margin_inline_start() const;
    void margin_inline_start(const jsbind::String& value);
    jsbind::String margin_inline_end() const;
    void margin_inline_end(const jsbind::String& value);
    jsbind::String inset() const;
    void inset(const jsbind::String& value);
    jsbind::String insetBlock() const;
    void insetBlock(const jsbind::String& value);
    jsbind::String insetBlockStart() const;
    void insetBlockStart(const jsbind::String& value);
    jsbind::String insetBlockEnd() const;
    void insetBlockEnd(const jsbind::String& value);
    jsbind::String insetInline() const;
    void insetInline(const jsbind::String& value);
    jsbind::String insetInlineStart() const;
    void insetInlineStart(const jsbind::String& value);
    jsbind::String insetInlineEnd() const;
    void insetInlineEnd(const jsbind::String& value);
    jsbind::String top() const;
    void top(const jsbind::String& value);
    jsbind::String left() const;
    void left(const jsbind::String& value);
    jsbind::String right() const;
    void right(const jsbind::String& value);
    jsbind::String bottom() const;
    void bottom(const jsbind::String& value);
    jsbind::String inset_block() const;
    void inset_block(const jsbind::String& value);
    jsbind::String inset_block_start() const;
    void inset_block_start(const jsbind::String& value);
    jsbind::String inset_block_end() const;
    void inset_block_end(const jsbind::String& value);
    jsbind::String inset_inline() const;
    void inset_inline(const jsbind::String& value);
    jsbind::String inset_inline_start() const;
    void inset_inline_start(const jsbind::String& value);
    jsbind::String inset_inline_end() const;
    void inset_inline_end(const jsbind::String& value);
    jsbind::String width() const;
    void width(const jsbind::String& value);
    jsbind::String minWidth() const;
    void minWidth(const jsbind::String& value);
    jsbind::String maxWidth() const;
    void maxWidth(const jsbind::String& value);
    jsbind::String height() const;
    void height(const jsbind::String& value);
    jsbind::String minHeight() const;
    void minHeight(const jsbind::String& value);
    jsbind::String maxHeight() const;
    void maxHeight(const jsbind::String& value);
    jsbind::String blockSize() const;
    void blockSize(const jsbind::String& value);
    jsbind::String minBlockSize() const;
    void minBlockSize(const jsbind::String& value);
    jsbind::String maxBlockSize() const;
    void maxBlockSize(const jsbind::String& value);
    jsbind::String inlineSize() const;
    void inlineSize(const jsbind::String& value);
    jsbind::String minInlineSize() const;
    void minInlineSize(const jsbind::String& value);
    jsbind::String maxInlineSize() const;
    void maxInlineSize(const jsbind::String& value);
    jsbind::String min_width() const;
    void min_width(const jsbind::String& value);
    jsbind::String max_width() const;
    void max_width(const jsbind::String& value);
    jsbind::String min_height() const;
    void min_height(const jsbind::String& value);
    jsbind::String max_height() const;
    void max_height(const jsbind::String& value);
    jsbind::String block_size() const;
    void block_size(const jsbind::String& value);
    jsbind::String min_block_size() const;
    void min_block_size(const jsbind::String& value);
    jsbind::String max_block_size() const;
    void max_block_size(const jsbind::String& value);
    jsbind::String inline_size() const;
    void inline_size(const jsbind::String& value);
    jsbind::String min_inline_size() const;
    void min_inline_size(const jsbind::String& value);
    jsbind::String max_inline_size() const;
    void max_inline_size(const jsbind::String& value);
    jsbind::String placeSelf() const;
    void placeSelf(const jsbind::String& value);
    jsbind::String alignSelf() const;
    void alignSelf(const jsbind::String& value);
    jsbind::String justifySelf() const;
    void justifySelf(const jsbind::String& value);
    jsbind::String place_self() const;
    void place_self(const jsbind::String& value);
    jsbind::String align_self() const;
    void align_self(const jsbind::String& value);
    jsbind::String justify_self() const;
    void justify_self(const jsbind::String& value);
    jsbind::String positionAnchor() const;
    void positionAnchor(const jsbind::String& value);
    jsbind::String position_anchor() const;
    void position_anchor(const jsbind::String& value);
    jsbind::String positionArea() const;
    void positionArea(const jsbind::String& value);
    jsbind::String position_area() const;
    void position_area(const jsbind::String& value);
};

